Algoritmo "Entrada e Saida de Dados"

// Descrição   : Entrada e Saida de Dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/12/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("digite o seu nome: ")
   leia(nome)
   escreva("digite o sua nota: ")
   leia(nota)

   escreval("nome digitado foi: ", nome)
   escreval("a nota digitada foi: ", nota)

Fimalgoritmo